### ISSUE TITLE
Multiple targets with the same identifier is not supported.

### ISSUE THREAD

**Issue by antonnyman** [antonnyman/embroidery#8]
⚠️ This is from the new typescript api!
Example:
```html
<!--- template -->
<div data-controller="multiple">
  <button data-action="greet">Greet</button>
  <span data-target="hello">Hello to you</span>
  <span data-target="hello">Hello to me</span>
</div>
```
```js
export const multiple = {
  greet({ hello }) { // <- Only returns the last target
    console.log(hello.innerHTML) // Result: "Hello to me"
  }
}
```

We should support data targets that share the same identifier as an array, for example:

```js
export const multiple = {
  greet({ hellos }){ // Should we pluralize identifiers if there are multiple (like stimulus)?
    hellos.map(hello => console.log(hello.innerHTML))
  }
}
```

**Comment by Skalman** [comment]
Automatic pluralization is dangerous and difficult. E.g. potato -> potato**es**; taco -> taco**s**.

If you want to be inspired by PHP form submission, while failing fast when the developer does something wrong:
- Multiple targets must end with `[]`, e.g. `<span data-target="hellos[]">`
- If there are multiple `<span data-target="hellos">`, throw an error (notice the missing `[]`)

**Comment by antonnyman** [comment]
I solved this by adding like you said `hellos[]`. I wanted to keep the destructuring in the controllers, so when you access an array of targets you have to use `helloTargets`. See updated README. :)
