### ISSUE TITLE
Support or enforce casing?

### ISSUE THREAD

**Issue by antonnyman** [antonnyman/embroidery#9]
Today you can only write controllers with camelCasing.

✅ 
```html
<div data-controller="myController"></div>
```

❌
```html
<div data-controller="my-controller"></div>
<div data-controller="my_controller"></div>
```

Should we support multiple types of casing or only support camelCase?

**Comment by Skalman** [comment]
I don't actually see how you're preventing `my-controller` and `my_controller` today. Won't these work?

```js
import { Embroidery } from 'embroidery'
import { myController } from 'my-controller'
import { myController2 } from 'my-controller2'
import { myController3 } from 'my-controller3'
let app = Embroidery.start()
app.register({
  myController,
  'my-controller': myController2,
  my_controller: myController3,
})
```

**Comment by antonnyman** [comment]
That's right. Although if we sometime in the future want to support automatic controller registration (with webpack an fs) we might have to transform the casing to be correct.
